workflows of continuos deployment

diff --git a/.github/workflows/packer-validate.yml b/.github/workflows/packer-validate.yml
--- a/.github/workflows/packer-validate.yml
+++ b/.github/workflows/packer-validate.yml
@@ -32,6 +32,15 @@ jobs:
            cd backend
            echo `pwd`   
            echo `ls`
+           
+      - name: Check if Packer file exists
+        run: |
+             if [ -f "ami.us-east-1.pkr.hcl" ]; then
+               echo "Packer file found."
+             else
+               echo "Packer file not found. Check the file location."
+               exit 1
+             fi
 
       - name: Initialize Packer
         run: packer init .
